In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("./Train_samsung.csv")

In [3]:
df.head()

X1   X2 X3        X4  X5    X6      X7     X8     X9  X10        X11  \
0  Male  Yes  0  Graduate  No  6000  2250.0  265.0  360.0  NaN  Semiurban   
1  Male  Yes  0  Graduate  No  2958  2900.0  131.0  360.0  1.0  Semiurban   
2  Male  Yes  2  Graduate  No  6250  1695.0  210.0  360.0  1.0  Semiurban   
3  Male  Yes  0  Graduate  No  2083  3150.0  128.0  360.0  1.0  Semiurban   
4  Male   No  0  Graduate  No  4166     0.0   98.0  360.0  0.0  Semiurban   

  Class  
0     N  
1     Y  
2     Y  
3     Y  
4     N

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 491 entries, 0 to 490
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   X1      479 non-null    object 
 1   X2      490 non-null    object 
 2   X3      480 non-null    object 
 3   X4      491 non-null    object 
 4   X5      467 non-null    object 
 5   X6      491 non-null    int64  
 6   X7      491 non-null    float64
 7   X8      475 non-null    float64
 8   X9      479 non-null    float64
 9   X10     451 non-null    float64
 10  X11     491 non-null    object 
 11  Class   491 non-null    object 
dtypes: float64(4), int64(1), object(7)
memory usage: 46.2+ KB


In [5]:
df.describe(include="all")

X1   X2   X3        X4   X5            X6            X7          X8  \
count    479  490  480       491  467    491.000000    491.000000  475.000000   
unique     2    2    4         2    2           NaN           NaN         NaN   
top     Male  Yes    0  Graduate   No           NaN           NaN         NaN   
freq     386  311  282       382  400           NaN           NaN         NaN   
mean     NaN  NaN  NaN       NaN  NaN   5502.645621   1676.488635  148.722105   
std      NaN  NaN  NaN       NaN  NaN   5932.951396   3177.641499   87.719000   
min      NaN  NaN  NaN       NaN  NaN    150.000000      0.000000   17.000000   
25%      NaN  NaN  NaN       NaN  NaN   2918.500000      0.000000  100.000000   
50%      NaN  NaN  NaN       NaN  NaN   3900.000000   1126.000000  129.000000   
75%      NaN  NaN  NaN       NaN  NaN   5938.000000   2333.000000  168.000000   
max      NaN  NaN  NaN       NaN  NaN  81000.000000  41667.000000  700.000000   

                X9         X10        X11 Class  
count   479.000000  451.000000        491   491  
unique         NaN         NaN          3     2  
top            NaN         NaN  Semiurban     Y  
freq           NaN         NaN        191   342  
mean    340.283925    0.844789        NaN   NaN  
std      67.708849    0.362507        NaN   NaN  
min      12.000000    0.000000        NaN   NaN  
25%     360.000000    1.000000        NaN   NaN  
50%     360.000000    1.000000        NaN   NaN  
75%     360.000000    1.000000        NaN   NaN  
max     480.000000    1.000000        NaN   NaN

In [6]:
df1=df.copy()

In [7]:
df_1 = df.fillna(df.mean())

C:\Users\anhdu\AppData\Local\Temp\ipykernel_13088\2851590108.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_1 = df.fillna(df.mean())


In [8]:
def fillna(col):
    col.fillna(col.value_counts().index[0], inplace=True)
    return col
df_1=df_1.apply(lambda col:fillna(col))
df_1

X1   X2 X3            X4   X5     X6      X7          X8     X9  \
0      Male  Yes  0      Graduate   No   6000  2250.0  265.000000  360.0   
1      Male  Yes  0      Graduate   No   2958  2900.0  131.000000  360.0   
2      Male  Yes  2      Graduate   No   6250  1695.0  210.000000  360.0   
3      Male  Yes  0      Graduate   No   2083  3150.0  128.000000  360.0   
4      Male   No  0      Graduate   No   4166     0.0   98.000000  360.0   
..      ...  ... ..           ...  ...    ...     ...         ...    ...   
486    Male  Yes  2  Not Graduate  Yes   1875  1875.0   97.000000  360.0   
487    Male  Yes  2      Graduate   No  11417  1126.0  225.000000  360.0   
488  Female   No  0      Graduate   No   3237     0.0   30.000000  360.0   
489  Female  Yes  0      Graduate   No  10047     0.0  148.722105  240.0   
490    Male  Yes  0      Graduate   No  13650     0.0  148.722105  360.0   

          X10        X11 Class  
0    0.844789  Semiurban     N  
1    1.000000  Semiurban     Y  
2    1.000000  Semiurban     Y  
3    1.000000  Semiurban     Y  
4    0.000000  Semiurban     N  
..        ...        ...   ...  
486  1.000000  Semiurban     Y  
487  1.000000      Urban     Y  
488  1.000000      Urban     Y  
489  1.000000  Semiurban     Y  
490  1.000000      Urban     Y  

[491 rows x 12 columns]

In [9]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 491 entries, 0 to 490
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   X1      491 non-null    object 
 1   X2      491 non-null    object 
 2   X3      491 non-null    object 
 3   X4      491 non-null    object 
 4   X5      491 non-null    object 
 5   X6      491 non-null    int64  
 6   X7      491 non-null    float64
 7   X8      491 non-null    float64
 8   X9      491 non-null    float64
 9   X10     491 non-null    float64
 10  X11     491 non-null    object 
 11  Class   491 non-null    object 
dtypes: float64(4), int64(1), object(7)
memory usage: 46.2+ KB


In [10]:
df_2 = df_1.copy()
train = df_1.copy()

In [11]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.model_selection import train_test_split

In [12]:
label=LabelEncoder()
for c in  df_2.columns:
    if(df_2[c].dtype=='object'):
        train[c]=label.fit_transform(df_2[c])
    else:
        train[c]=df_2[c]

train

X1  X2  X3  X4  X5     X6      X7          X8     X9       X10  X11  \
0     1   1   0   0   0   6000  2250.0  265.000000  360.0  0.844789    1   
1     1   1   0   0   0   2958  2900.0  131.000000  360.0  1.000000    1   
2     1   1   2   0   0   6250  1695.0  210.000000  360.0  1.000000    1   
3     1   1   0   0   0   2083  3150.0  128.000000  360.0  1.000000    1   
4     1   0   0   0   0   4166     0.0   98.000000  360.0  0.000000    1   
..   ..  ..  ..  ..  ..    ...     ...         ...    ...       ...  ...   
486   1   1   2   1   1   1875  1875.0   97.000000  360.0  1.000000    1   
487   1   1   2   0   0  11417  1126.0  225.000000  360.0  1.000000    2   
488   0   0   0   0   0   3237     0.0   30.000000  360.0  1.000000    2   
489   0   1   0   0   0  10047     0.0  148.722105  240.0  1.000000    1   
490   1   1   0   0   0  13650     0.0  148.722105  360.0  1.000000    2   

     Class  
0        0  
1        1  
2        1  
3        1  
4        0  
..     ...  
486      1  
487      1  
488      1  
489      1  
490      1  

[491 rows x 12 columns]

In [13]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.model_selection import train_test_split

In [14]:
#Liên tục hóa thuộc tính
label=LabelEncoder()
for c in  df_2.columns:
    if(df_2[c].dtype=='object'):
        train[c]=label.fit_transform(df_2[c])
    else:
        train[c]=df_2[c]

train

X1  X2  X3  X4  X5     X6      X7          X8     X9       X10  X11  \
0     1   1   0   0   0   6000  2250.0  265.000000  360.0  0.844789    1   
1     1   1   0   0   0   2958  2900.0  131.000000  360.0  1.000000    1   
2     1   1   2   0   0   6250  1695.0  210.000000  360.0  1.000000    1   
3     1   1   0   0   0   2083  3150.0  128.000000  360.0  1.000000    1   
4     1   0   0   0   0   4166     0.0   98.000000  360.0  0.000000    1   
..   ..  ..  ..  ..  ..    ...     ...         ...    ...       ...  ...   
486   1   1   2   1   1   1875  1875.0   97.000000  360.0  1.000000    1   
487   1   1   2   0   0  11417  1126.0  225.000000  360.0  1.000000    2   
488   0   0   0   0   0   3237     0.0   30.000000  360.0  1.000000    2   
489   0   1   0   0   0  10047     0.0  148.722105  240.0  1.000000    1   
490   1   1   0   0   0  13650     0.0  148.722105  360.0  1.000000    2   

     Class  
0        0  
1        1  
2        1  
3        1  
4        0  
..     ...  
486      1  
487      1  
488      1  
489      1  
490      1  

[491 rows x 12 columns]

In [15]:
from sklearn.preprocessing import MinMaxScaler

In [16]:

columns_to_normalize = ['X6','X7','X8','X9']
scaler = MinMaxScaler()
train[columns_to_normalize] = scaler.fit_transform(train[columns_to_normalize])

df_3 = train[columns_to_normalize]
df_3

X6        X7        X8        X9
0    0.072356  0.054000  0.363104  0.743590
1    0.034731  0.069599  0.166911  0.743590
2    0.075448  0.040680  0.282577  0.743590
3    0.023908  0.075599  0.162518  0.743590
4    0.049672  0.000000  0.118594  0.743590
..        ...       ...       ...       ...
486  0.021336  0.045000  0.117130  0.743590
487  0.139357  0.027024  0.304539  0.743590
488  0.038182  0.000000  0.019034  0.743590
489  0.122412  0.000000  0.192858  0.487179
490  0.166976  0.000000  0.192858  0.743590

[491 rows x 4 columns]

In [17]:
train

X1  X2  X3  X4  X5        X6        X7        X8        X9       X10  \
0     1   1   0   0   0  0.072356  0.054000  0.363104  0.743590  0.844789   
1     1   1   0   0   0  0.034731  0.069599  0.166911  0.743590  1.000000   
2     1   1   2   0   0  0.075448  0.040680  0.282577  0.743590  1.000000   
3     1   1   0   0   0  0.023908  0.075599  0.162518  0.743590  1.000000   
4     1   0   0   0   0  0.049672  0.000000  0.118594  0.743590  0.000000   
..   ..  ..  ..  ..  ..       ...       ...       ...       ...       ...   
486   1   1   2   1   1  0.021336  0.045000  0.117130  0.743590  1.000000   
487   1   1   2   0   0  0.139357  0.027024  0.304539  0.743590  1.000000   
488   0   0   0   0   0  0.038182  0.000000  0.019034  0.743590  1.000000   
489   0   1   0   0   0  0.122412  0.000000  0.192858  0.487179  1.000000   
490   1   1   0   0   0  0.166976  0.000000  0.192858  0.743590  1.000000   

     X11  Class  
0      1      0  
1      1      1  
2      1      1  
3      1      1  
4      1      0  
..   ...    ...  
486    1      1  
487    2      1  
488    2      1  
489    1      1  
490    2      1  

[491 rows x 12 columns]

In [18]:
df_4 = train.copy()

In [19]:
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

In [20]:
X1 = df_4.iloc[:,:-1]
y = df_4.iloc[:,-1]

In [21]:
X, y = df_4.drop('Class', axis=1).values, df_4['Class'].values

In [22]:
y

array([0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,

In [23]:
#giảm chiều dữ liệu
n_comp = 3
tsne = TSNE(n_components = n_comp, init='pca', random_state=1001, perplexity=30, method='barnes_hut')
#tsne = TSNE(n_components=2, learning_rate='auto',init='random', perplexity=3)
X_reduced = tsne.fit_transform(X)
X_reduced.shape  

(491, 3)

In [24]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

In [25]:
X

array([[1.        , 1.        , 0.        , ..., 0.74358974, 0.84478936,
        1.        ],
       [1.        , 1.        , 0.        , ..., 0.74358974, 1.        ,
        1.        ],
       [1.        , 1.        , 2.        , ..., 0.74358974, 1.        ,
        1.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.74358974, 1.        ,
        2.        ],
       [0.        , 1.        , 0.        , ..., 0.48717949, 1.        ,
        1.        ],
       [1.        , 1.        , 0.        , ..., 0.74358974, 1.        ,
        2.        ]])

In [26]:
y

array([0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,

In [27]:
X_train, X_test,y_train, y_test = train_test_split(X,y ,random_state=104, test_size=0.2, shuffle=True)

In [28]:
clf = SVC(kernel = 'linear')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print("SVM accuracy: ", accuracy_score(y_test, y_pred))
print("SVM f1 score: ", f1_score(y_test, y_pred, average='weighted'))
print("SVM confusion matrix: ")
print(confusion_matrix(y_test, y_pred))

SVM accuracy:  0.8585858585858586
SVM f1 score:  0.843309639605936
SVM confusion matrix: 
[[11 12]
 [ 2 74]]


In [29]:
test = pd.read_csv("./Test_samsung_noclass.csv")

In [30]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   X1      122 non-null    object 
 1   X2      121 non-null    object 
 2   X3      119 non-null    object 
 3   X4      123 non-null    object 
 4   X5      115 non-null    object 
 5   X6      123 non-null    int64  
 6   X7      123 non-null    float64
 7   X8      117 non-null    float64
 8   X9      121 non-null    float64
 9   X10     113 non-null    float64
 10  X11     123 non-null    object 
dtypes: float64(4), int64(1), object(6)
memory usage: 10.7+ KB


In [31]:
df_11 = test.fillna(test.mean())
def fillna(col):
    col.fillna(col.value_counts().index[0], inplace=True)
    return col

df_11=df_11.apply(lambda col:fillna(col))
df_21 = df_11.copy()
train1 = df_11.copy()

label=LabelEncoder()

for c in  df_21.columns:
    if(df_21[c].dtype=='object'):
        train1[c]=label.fit_transform(df_21[c])
    else:
        train1[c]=df_21[c]

train1

C:\Users\anhdu\AppData\Local\Temp\ipykernel_13088\4113856060.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_11 = test.fillna(test.mean())


X1  X2  X3  X4  X5     X6      X7     X8     X9       X10  X11
0     1   1   0   0   0   9083     0.0  228.0  360.0  1.000000    1
1     1   1   0   0   0   4310     0.0  130.0  360.0  0.831858    1
2     1   1   2   0   0   4167  1447.0  158.0  360.0  1.000000    0
3     0   0   0   0   0   2900     0.0   71.0  360.0  1.000000    0
4     1   0   0   0   0   2718     0.0   70.0  360.0  1.000000    1
..   ..  ..  ..  ..  ..    ...     ...    ...    ...       ...  ...
118   1   1   0   0   0   3716     0.0   42.0  180.0  1.000000    0
119   0   0   0   0   0   2507     0.0   56.0  360.0  1.000000    0
120   1   1   1   0   0   2882  1843.0  123.0  480.0  1.000000    1
121   1   1   2   0   0   2500  1840.0  109.0  360.0  1.000000    2
122   1   1   0   0   0  63337     0.0  490.0  180.0  1.000000    2

[123 rows x 11 columns]

In [32]:
columns_to_normalize = ['X6','X7','X8','X9']
scaler = MinMaxScaler()
train1[columns_to_normalize] = scaler.fit_transform(train1[columns_to_normalize])

df_6 = train1[columns_to_normalize]
df_6

X6        X7        X8        X9
0    0.134194  0.000000  0.370558  0.696970
1    0.058025  0.000000  0.204738  0.696970
2    0.055743  0.186710  0.252115  0.696970
3    0.035523  0.000000  0.104907  0.696970
4    0.032619  0.000000  0.103215  0.696970
..        ...       ...       ...       ...
118  0.048545  0.000000  0.055838  0.242424
119  0.029252  0.000000  0.079526  0.696970
120  0.035236  0.237806  0.192893  1.000000
121  0.029140  0.237419  0.169205  0.696970
122  1.000000  0.000000  0.813875  0.242424

[123 rows x 4 columns]

In [33]:
train1

X1  X2  X3  X4  X5        X6        X7        X8        X9       X10  X11
0     1   1   0   0   0  0.134194  0.000000  0.370558  0.696970  1.000000    1
1     1   1   0   0   0  0.058025  0.000000  0.204738  0.696970  0.831858    1
2     1   1   2   0   0  0.055743  0.186710  0.252115  0.696970  1.000000    0
3     0   0   0   0   0  0.035523  0.000000  0.104907  0.696970  1.000000    0
4     1   0   0   0   0  0.032619  0.000000  0.103215  0.696970  1.000000    1
..   ..  ..  ..  ..  ..       ...       ...       ...       ...       ...  ...
118   1   1   0   0   0  0.048545  0.000000  0.055838  0.242424  1.000000    0
119   0   0   0   0   0  0.029252  0.000000  0.079526  0.696970  1.000000    0
120   1   1   1   0   0  0.035236  0.237806  0.192893  1.000000  1.000000    1
121   1   1   2   0   0  0.029140  0.237419  0.169205  0.696970  1.000000    2
122   1   1   0   0   0  1.000000  0.000000  0.813875  0.242424  1.000000    2

[123 rows x 11 columns]

In [34]:
y_pred_1 = clf.predict(train1)
y_pred_1

C:\Users\anhdu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:457: UserWarning: X has feature names, but SVC was fitted without feature names
  warnings.warn(


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [35]:
result = pd.DataFrame(y_pred_1, columns = ['Class'])

In [36]:
test_1 = pd.concat([train1, result], axis=1)

In [37]:
test_1

X1  X2  X3  X4  X5        X6        X7        X8        X9       X10  \
0     1   1   0   0   0  0.134194  0.000000  0.370558  0.696970  1.000000   
1     1   1   0   0   0  0.058025  0.000000  0.204738  0.696970  0.831858   
2     1   1   2   0   0  0.055743  0.186710  0.252115  0.696970  1.000000   
3     0   0   0   0   0  0.035523  0.000000  0.104907  0.696970  1.000000   
4     1   0   0   0   0  0.032619  0.000000  0.103215  0.696970  1.000000   
..   ..  ..  ..  ..  ..       ...       ...       ...       ...       ...   
118   1   1   0   0   0  0.048545  0.000000  0.055838  0.242424  1.000000   
119   0   0   0   0   0  0.029252  0.000000  0.079526  0.696970  1.000000   
120   1   1   1   0   0  0.035236  0.237806  0.192893  1.000000  1.000000   
121   1   1   2   0   0  0.029140  0.237419  0.169205  0.696970  1.000000   
122   1   1   0   0   0  1.000000  0.000000  0.813875  0.242424  1.000000   

     X11  Class  
0      1      1  
1      1      1  
2      0      1  
3      0      1  
4      1      1  
..   ...    ...  
118    0      1  
119    0      1  
120    1      1  
121    2      1  
122    2      1  

[123 rows x 12 columns]

In [38]:
test_1.to_csv('Nhom_23.csv')